#!/bin/python3
import math
import sys

def lowestTriangle(base, area):
    # Complete this function
    h = (2*area)/base
    return math.ceil(h)

base, area = input().strip().split(' ')
base, area = [int(base), int(area)]
height = lowestTriangle(base, area)
print(height)

